# Generated by Django 2.1 on 2018-08-13 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publushed_date',
            new_name='published_date',
        ),
    ]
